### ISSUE TITLE
Showing only information from current screen

### ISSUE THREAD

**Issue by matiux** [antroids/application-title-bar#8]
As with other similar applets, might it be possible to manage this behavior?
I have two monitors with two menu bar. Putting the applet in each menu bar, I would like to see title and button only for the window in the current screen.

**Comment by antroids** [comment]
Implemented in 0.3.2, uploaded to the Store.
I didn't find where to take Virtual Desktop id, but filtering by Activity and Screen should work well.

**Comment by Kasi07** [comment]
First, thanks for all your work!

I found a bug with this feature. 
My setup: 2 Displays which both have the plasmoid in a top bar installed.
When I move a window to another display, it will then activate the widget on the display I moved it too but not remove it from the old one. This only changes if I focus another window.

**Comment by antroids** [comment]
Thanks for your report!
This should be resolved in the 0.3.6.

**Comment by Kasi07** [comment]
So I upgraded to the new version but it seems like the bug persists.

**Comment by antroids** [comment]
Could you restart plasma and check again.
`plasmashell --replace &`

**Comment by Kasi07** [comment]
I installed, restarted the plasmashell, checked for the correct version and when it didn't work I even restarted my PC just to be sure.

**Comment by D3SOX** [comment]
I think there's a bit of confusion here. @antroids you implemented filtering by Virtual Desktops but Plasma does not attach them to a monitor, so Virtual Desktop 1 is Virtual Desktop 1 on every screen simultaneously.

More context in similar projects:
https://github.com/dhruv8sh/plasma6-window-title-applet/issues/6
https://github.com/moodyhunter/applet-window-buttons6/issues/4

**Comment by antroids** [comment]
> I installed, restarted the plasmashell, checked for the correct version and when it didn't work I even restarted my PC just to be sure.

Could you please check the 0.3.7.
If the bug still persists, could you attach OS and Plasma version details from About this system screen.

**Comment by antroids** [comment]
> I think there's a bit of confusion here. @antroids you implemented filtering by Virtual Desktops but Plasma does not attach them to a monitor, so Virtual Desktop 1 is Virtual Desktop 1 on every screen simultaneously.
> 
> More context in similar projects: [dhruv8sh/plasma6-window-title-applet#6](https://github.com/dhruv8sh/plasma6-window-title-applet/issues/6) [moodyhunter/applet-window-buttons6#4](https://github.com/moodyhunter/applet-window-buttons6/issues/4)

No, there was a bug with moving from one screen to another.

And yes, it would be nice to have an option to show buttons for top task for each screen, how it was in Unity.
I could try to show lastActive task, like it's implemented in widgets from your links, but not sure that it will be the same.

**Comment by Kasi07** [comment]
This is working now, thanks alot!

**Comment by antroids** [comment]
**Help wanted!**
![download](https://github.com/antroids/application-title-bar/assets/36043354/c1972d4e-e308-41d1-9ea5-c643a035de35)

I added some nice features for multiple screens, but got segmentation faults during development (yeah, sure, nothing wrong with CPP, it's just used incorrectly).
It seems that the issue was fixed, but I would like to test it well.
So, in [Release 0.3.8](https://github.com/antroids/application-title-bar/releases/tag/v0.3.8) I added an option to show last active task, not the current one. It can be activated on Behaviour options tab.

![image](https://github.com/antroids/application-title-bar/assets/36043354/d171a86e-0fa6-4fd7-8380-133b2ee579d9)

Could you please install the new version via  "Add Widgets..." -> "Get New Widgets..." -> "Install Widget From Local file" -> load *.plasmoid file and check how it works.

**Comment by antroids** [comment]
> Although I found a small bug. Replication steps:
> 
> 1. open two windows of the same program on one display
> 2. Try to close using the applet close button
> 3. Both windows are being closed instead of just the last active one.

Good catch! 
The bug is confirmed: https://github.com/antroids/application-title-bar/issues/16
It seems there is a window group in the tasks list.
